#!/bin/bash

THEN=0

CPCACHE_URL="$(sed -ne 's/^Server = \(.*\)\/\$repo.*#\s\+\!cpcache/\1/p' /etc/pacman.d/mirrorlist | head -n1)"
if [ -z "$CPCACHE_URL" ]; then
    >&2 echo "Unable to find cpcache mirror in /etc/pacman.d/mirrorlist"
    >&2 echo "Please ensure that one entry exists with a trailing !cpcache comment."
    exit 1
fi

while read -r line; do
    if [ "$line" = "db.lck" ]; then
        while pgrep -u root pacman > /dev/null; do
            sleep .1;
        done
        NOW="$(date +%s)"
        DIFF=$((NOW-THEN))
        if [ $DIFF -ge 1 ]; then
            pacman -Qq | curl --data-binary @- "$CPCACHE_URL/$(uname -m)/$(hostname)" -H 'Content-Type:text/plain; charset=utf8'
            echo "pacman finished."
        fi
        THEN="$NOW"
    fi
done < <(inotifywait -qm /var/lib/pacman -e DELETE --format %f)
