[core]
    pkg_url = "http://127.0.0.1:7070/core/os/x86_64/"
    local_directory = "/var/cache/cpcache/pkg/core/os/x86_64"
[extra]
    pkg_url = "http://127.0.0.1:7070/extra/os/x86_64/"
    local_directory = "/var/cache/cpcache/pkg/extra/os/x86_64"
[community]
    pkg_url = "http://127.0.0.1:7070/community/os/x86_64/"
    local_directory = "/var/cache/cpcache/pkg/community/os/x86_64"
[multilib]
    pkg_url = "http://127.0.0.1:7070/multilib/os/x86_64/"
    local_directory = "/var/cache/cpcache/pkg/multilib/os/x86_64"
